// GENERATED by scripts/build-tracking-data.mjs — do not edit.
//
// Source: vendor/tracking-number-data (MIT, jkeen/tracking_number_data).
// See vendor/tracking-number-data/PINNED.md for the pinned commit and why
// this is vendored rather than depended on.
//
// Run `npm run build:tracking` after updating the vendored data.

export interface Checksum {
  name: string;
  evens: number | null;
  odds: number | null;
  reverse: boolean;
  weightings: number[] | null;
  modulo1: number | null;
  modulo2: number | null;
}

/** An implied prefix re-attached to the serial before the check digit is computed. */
export interface PrependIf {
  /** Apply the prefix only when the serial does NOT already match this. */
  unless: string;
  content: string;
}

export interface TrackingPattern {
  id: string;
  /** The carrier this number belongs to, as a human reads it. */
  courier: string;
  courierCode: string;
  name: string;
  /** Regex source. Tolerates whitespace between characters, as printed labels do. */
  source: string;
  /** `%s` is replaced with the number. Null where the carrier publishes none. */
  url: string | null;
  checksum: Checksum | null;
  prependIf: PrependIf | null;
}

export const PATTERNS: readonly TrackingPattern[] = [
  {
    "id": "amazon_logistics",
    "courier": "Amazon",
    "courierCode": "amazon",
    "name": "Amazon Logistics",
    "source": "\\s*T\\s*B\\s*[ACM]\\s*(?<SerialNumber>([0-9]\\s*){12,12})\\s*",
    "url": null,
    "checksum": null,
    "prependIf": null
  },
  {
    "id": "amazon_international",
    "courier": "Amazon",
    "courierCode": "amazon",
    "name": "Amazon International",
    "source": "\\s*[AFC]\\s*(?<SerialNumber>([0-9]\\s*){10,10})\\s*",
    "url": null,
    "checksum": null,
    "prependIf": null
  },
  {
    "id": "canada_post",
    "courier": "Canada Post",
    "courierCode": "canada_post",
    "name": "Canada Post (16)",
    "source": "\\s*(?<SerialNumber>(?<OriginId>([0-9]\\s*){7})([0-9]\\s*){8})(?<CheckDigit>[0-9]\\s*)",
    "url": "https://www.canadapost-postescanada.ca/track-reperage/en#/search?searchFor=%s",
    "checksum": {
      "name": "mod10",
      "evens": 3,
      "odds": 1,
      "reverse": false,
      "weightings": null,
      "modulo1": null,
      "modulo2": null
    },
    "prependIf": null
  },
  {
    "id": "dhl_express",
    "courier": "DHL",
    "courierCode": "dhl",
    "name": "DHL Express",
    "source": "\\s*(?<SerialNumber>([0-9]\\s*){9,10})(?<CheckDigit>([0-9]\\s*))",
    "url": "http://www.dhl.com/en/express/tracking.html?brand=DHL&AWB=%s",
    "checksum": {
      "name": "mod7",
      "evens": null,
      "odds": null,
      "reverse": false,
      "weightings": null,
      "modulo1": null,
      "modulo2": null
    },
    "prependIf": null
  },
  {
    "id": "dhl_express_piece_id",
    "courier": "DHL",
    "courierCode": "dhl",
    "name": "DHL Express (Piece ID)",
    "source": "\\s*(J[A-Z]{2,3})(?<SerialNumber>([0-9]\\s*){9,10})",
    "url": "http://www.dhl.com/en/express/tracking.html?brand=DHL&AWB=%s",
    "checksum": null,
    "prependIf": null
  },
  {
    "id": "dhl_ecommerce",
    "courier": "DHL",
    "courierCode": "dhl",
    "name": "DHL E-Commerce",
    "source": "(?:GM|LX|RX|UV|CN|SG|TH|IN|HK|MY)\\s*(?<SerialNumber>(?=[0-9A-Z\\s]{10,39}\\b)(?=[^0-9A-Z]*[0-9])[0-9A-Z\\s]{10,39})",
    "url": "http://www.dhl.com/en/express/tracking.html?brand=DHL&AWB=%s",
    "checksum": null,
    "prependIf": null
  },
  {
    "id": "dhl_ecommerce_14",
    "courier": "DHL",
    "courierCode": "dhl",
    "name": "DHL E-Commerce (14)",
    "source": "\\s*\\b(?<SerialNumber>(?:[0-9]\\s*){14})\\b",
    "url": "http://www.dhl.com/en/express/tracking.html?brand=DHL&AWB=%s",
    "checksum": null,
    "prependIf": null
  },
  {
    "id": "dhl_ecommerce_30",
    "courier": "DHL",
    "courierCode": "dhl",
    "name": "DHL E-Commerce (30)",
    "source": "\\s*(?<RoutingApplicationId>4\\s*2\\s*0\\s*)(?<DestinationZip>([0-9]\\s*){5})(?!\\s*9\\s*[1-5]\\b)(?<SerialNumber>(?<ServiceType>(9[2-5]\\s*))(?<ShipperId>([0-9]\\s*){9})(?<PackageId>([0-9]\\s*){10}))(?<CheckDigit>[0-9]\\s*)",
    "url": "https://ecommerceportal.dhl.com/track?trackingnumber=%s",
    "checksum": {
      "name": "mod10",
      "evens": 3,
      "odds": 1,
      "reverse": true,
      "weightings": null,
      "modulo1": null,
      "modulo2": null
    },
    "prependIf": null
  },
  {
    "id": "dpd",
    "courier": "DPD",
    "courierCode": "dpd",
    "name": "DPD (28)",
    "source": "\\s*(?<SerialNumber>(?<DestinationZip>([0-9]\\s*){7})([0-9]\\s*){14}(?<ServiceType>([0-9]\\s*){3})(?<CountryCode>([0-9]\\s*){3}))(?<CheckDigit>[0-9A-Z]\\s*)",
    "url": "https://www.dpdgroup.com/nl/mydpd/my-parcels/track?lang=en&parcelNumber=%s",
    "checksum": {
      "name": "mod_37_36",
      "evens": null,
      "odds": null,
      "reverse": false,
      "weightings": null,
      "modulo1": null,
      "modulo2": null
    },
    "prependIf": null
  },
  {
    "id": "dpd_14",
    "courier": "DPD",
    "courierCode": "dpd",
    "name": "DPD (14)",
    "source": "\\s*(?<SerialNumber>([0-9]\\s*){14})(?<CheckDigit>[0-9A-Z]\\s*)",
    "url": "https://www.dpdgroup.com/nl/mydpd/my-parcels/track?lang=en&parcelNumber=%s",
    "checksum": {
      "name": "mod_37_36",
      "evens": null,
      "odds": null,
      "reverse": false,
      "weightings": null,
      "modulo1": null,
      "modulo2": null
    },
    "prependIf": null
  },
  {
    "id": "fedex_12",
    "courier": "FedEx",
    "courierCode": "fedex",
    "name": "FedEx Express (12)",
    "source": "\\s*(?<SerialNumber>([0-9]\\s*){11})(?<CheckDigit>[0-9]\\s*)",
    "url": "https://www.fedex.com/apps/fedextrack/?tracknumbers=%s",
    "checksum": {
      "name": "sum_product_with_weightings_and_modulo",
      "evens": null,
      "odds": null,
      "reverse": false,
      "weightings": [
        3,
        1,
        7,
        3,
        1,
        7,
        3,
        1,
        7,
        3,
        1
      ],
      "modulo1": 11,
      "modulo2": 10
    },
    "prependIf": null
  },
  {
    "id": "fedex_34",
    "courier": "FedEx",
    "courierCode": "fedex",
    "name": "FedEx Express (34)",
    "source": "\\s*1\\s*0\\s*[0-9]\\s*[0-9]\\s*[0-9]\\s*([0-9]\\s*){10}(?<DestinationZip>([0-9]\\s*){5})(?<SerialNumber>([0-9]\\s*){13})(?<CheckDigit>[0-9]\\s*)",
    "url": "https://www.fedex.com/apps/fedextrack/?tracknumbers=%s",
    "checksum": {
      "name": "sum_product_with_weightings_and_modulo",
      "evens": null,
      "odds": null,
      "reverse": false,
      "weightings": [
        1,
        7,
        3,
        1,
        7,
        3,
        1,
        7,
        3,
        1,
        7,
        3,
        1
      ],
      "modulo1": 11,
      "modulo2": 10
    },
    "prependIf": null
  },
  {
    "id": "fedex_smartpost",
    "courier": "FedEx",
    "courierCode": "fedex",
    "name": "FedEx SmartPost",
    "source": "\\s*(?:(?:(?<RoutingApplicationId>4\\s*2\\s*0\\s*)(?<DestinationZip>([0-9]\\s*){5}))?(?<ApplicationIdentifier>9\\s*2\\s*))?(?<SerialNumber>(?<SCNC>6\\s*1\\s*)(?<ServiceType>2\\s*9\\s*)(?<ShipperId>([0-9]\\s*){8})(?<PackageId>([0-9]\\s*){11}|([0-9]\\s*){7}))(?<CheckDigit>([0-9]\\s*))",
    "url": "https://www.fedex.com/apps/fedextrack/?tracknumbers=%s",
    "checksum": {
      "name": "mod10",
      "evens": 3,
      "odds": 1,
      "reverse": false,
      "weightings": null,
      "modulo1": null,
      "modulo2": null
    },
    "prependIf": {
      "unless": "^(?!92).+",
      "content": "92"
    }
  },
  {
    "id": "fedex_ground",
    "courier": "FedEx",
    "courierCode": "fedex",
    "name": "FedEx Ground",
    "source": "\\s*(?<SerialNumber>([0-9]\\s*){14})(?<CheckDigit>([0-9]\\s*))",
    "url": "https://www.fedex.com/apps/fedextrack/?tracknumbers=%s",
    "checksum": {
      "name": "mod10",
      "evens": 1,
      "odds": 3,
      "reverse": false,
      "weightings": null,
      "modulo1": null,
      "modulo2": null
    },
    "prependIf": null
  },
  {
    "id": "fedex_ground_sscc_18",
    "courier": "FedEx",
    "courierCode": "fedex",
    "name": "FedEx Ground (SSCC-18)",
    "source": "\\s*(?<ShippingContainerType>([0-9]\\s*){2})(?<SerialNumber>([0-9]\\s*){15})(?<CheckDigit>[0-9]\\s*)",
    "url": "https://www.fedex.com/apps/fedextrack/?tracknumbers=%s",
    "checksum": {
      "name": "mod10",
      "evens": 3,
      "odds": 1,
      "reverse": false,
      "weightings": null,
      "modulo1": null,
      "modulo2": null
    },
    "prependIf": null
  },
  {
    "id": "fedex_ground_96",
    "courier": "FedEx",
    "courierCode": "fedex",
    "name": "FedEx Ground 96 (22)",
    "source": "\\s*(?<ApplicationIdentifier>9\\s*6\\s*)(?<SCNC>([0-9]\\s*){2})(?<ServiceType>([0-9]\\s*){3})(?<SerialNumber>(?<ShipperId>([0-9]\\s*){7})(?<PackageId>([0-9]\\s*){7}))(?<CheckDigit>[0-9]\\s*)",
    "url": "https://www.fedex.com/apps/fedextrack/?tracknumbers=%s",
    "checksum": {
      "name": "mod10",
      "evens": 1,
      "odds": 3,
      "reverse": false,
      "weightings": null,
      "modulo1": null,
      "modulo2": null
    },
    "prependIf": null
  },
  {
    "id": "fedex_ground_gsn",
    "courier": "FedEx",
    "courierCode": "fedex",
    "name": "FedEx Ground GSN",
    "source": "\\s*(?<ApplicationIdentifier>9\\s*6\\s*)(?<SCNC>([0-9]\\s*){2})([0-9]\\s*){5}(?<GSN>([0-9]\\s*){10})[0-9]\\s*(?<SerialNumber>([0-9]\\s*){13})(?<CheckDigit>[0-9]\\s*)",
    "url": "https://www.fedex.com/apps/fedextrack/?tracknumbers=%s",
    "checksum": {
      "name": "sum_product_with_weightings_and_modulo",
      "evens": null,
      "odds": null,
      "reverse": false,
      "weightings": [
        1,
        7,
        3,
        1,
        7,
        3,
        1,
        7,
        3,
        1,
        7,
        3,
        1
      ],
      "modulo1": 11,
      "modulo2": 10
    },
    "prependIf": null
  },
  {
    "id": "landmark_global",
    "courier": "Landmark Global LTN",
    "courierCode": "landmark",
    "name": "Landmark Global LTN",
    "source": "\\s*L\\s*T\\s*N\\s*(?<SerialNumber>([0-9]\\s*){8})\\s*N\\s*1",
    "url": "https://track.landmarkglobal.com/?search=%s",
    "checksum": null,
    "prependIf": null
  },
  {
    "id": "lasership_lx",
    "courier": "LaserShip",
    "courierCode": "lasership",
    "name": "LaserShip LX",
    "source": "\\s*L\\s*[AIEHNX]\\s*[1-3]\\s*(?<SerialNumber>([0-9]\\s*){7,7})\\s*",
    "url": null,
    "checksum": null,
    "prependIf": null
  },
  {
    "id": "lasership_1ls7",
    "courier": "LaserShip",
    "courierCode": "lasership",
    "name": "LaserShip 1LS7 (15)",
    "source": "\\s*1\\s*L\\s*S\\s*7\\s*[12]\\s*([0-9]\\s*){4,4}(?<SerialNumber>([0-9]\\s*){6,6})\\s*",
    "url": null,
    "checksum": null,
    "prependIf": null
  },
  {
    "id": "lasership-LaserShip 1LS7 (18)",
    "courier": "LaserShip",
    "courierCode": "lasership",
    "name": "LaserShip 1LS7 (18)",
    "source": "\\s*1\\s*L\\s*S\\s*7\\s*[12]\\s*([0-9]\\s*){2,2}\\s*0\\s*1\\s*[1234]\\s*\\s*(?<SerialNumber>([0-9]\\s*){6,6})-\\s*1\\s*",
    "url": null,
    "checksum": null,
    "prependIf": null
  },
  {
    "id": "old_dominion-Old Dominion",
    "courier": "Old Dominion Freight Line",
    "courierCode": "old_dominion",
    "name": "Old Dominion",
    "source": "\\s*(?<SerialNumber>(7\\s*7\\s*[78]\\s*|0\\s*7\\s*2\\s*|7\\s*8\\s*0\\s*)([0-9]\\s*){7})(?<CheckDigit>[0-9]\\s*)",
    "url": "https://www.odfl.com/us/en/tools/trace-track-ltl-freight/trace.html?proNumbers=%s",
    "checksum": {
      "name": "luhn",
      "evens": null,
      "odds": null,
      "reverse": false,
      "weightings": null,
      "modulo1": null,
      "modulo2": null
    },
    "prependIf": null
  },
  {
    "id": "old_dominion-Old Dominion Guaranteed Shipment",
    "courier": "Old Dominion Freight Line",
    "courierCode": "old_dominion",
    "name": "Old Dominion Guaranteed Shipment",
    "source": "\\s*(?<SerialNumber>8\\s*0\\s*([0-9]\\s*){8})(?<CheckDigit>[0-9]\\s*)",
    "url": "https://www.odfl.com/us/en/tools/trace-track-ltl-freight/trace.html?proNumbers=%s",
    "checksum": {
      "name": "luhn",
      "evens": null,
      "odds": null,
      "reverse": false,
      "weightings": null,
      "modulo1": null,
      "modulo2": null
    },
    "prependIf": null
  },
  {
    "id": "ontrac_c",
    "courier": "OnTrac",
    "courierCode": "ontrac",
    "name": "OnTrac",
    "source": "\\s*C\\s*(?<SerialNumber>([0-9]\\s*){13})(?<CheckDigit>[0-9]\\s*)",
    "url": "http://www.ontrac.com/tracking/?number=%s",
    "checksum": {
      "name": "mod10",
      "evens": 1,
      "odds": 2,
      "reverse": false,
      "weightings": null,
      "modulo1": null,
      "modulo2": null
    },
    "prependIf": {
      "unless": "^(?!4).+$",
      "content": "4"
    }
  },
  {
    "id": "ontrac_d",
    "courier": "OnTrac",
    "courierCode": "ontrac",
    "name": "OnTrac D",
    "source": "\\s*D\\s*(?<SerialNumber>([0-9]\\s*){13})(?<CheckDigit>[0-9]\\s*)",
    "url": "http://www.ontrac.com/tracking/?number=%s",
    "checksum": {
      "name": "mod10",
      "evens": 1,
      "odds": 2,
      "reverse": false,
      "weightings": null,
      "modulo1": null,
      "modulo2": null
    },
    "prependIf": {
      "unless": "^(?!5).+$",
      "content": "5"
    }
  },
  {
    "id": "s10",
    "courier": "S10 International Standard",
    "courierCode": "s10",
    "name": "S10",
    "source": "\\s*(?<ServiceType>([A-Z]\\s*){2})(?<SerialNumber>([0-9]\\s*){8})(?<CheckDigit>([0-9]\\s*))(?<CountryCode>([A-Z]\\s*){2})",
    "url": null,
    "checksum": {
      "name": "s10",
      "evens": null,
      "odds": null,
      "reverse": false,
      "weightings": null,
      "modulo1": null,
      "modulo2": null
    },
    "prependIf": null
  },
  {
    "id": "ups",
    "courier": "UPS",
    "courierCode": "ups",
    "name": "UPS",
    "source": "\\s*1\\s*Z\\s*(?<SerialNumber>(?<ShipperId>(?:[A-Z0-9]\\s*){6,6})(?<ServiceType>(?:[A-Z0-9]\\s*){2,2})(?<PackageId>(?:[A-Z0-9]\\s*){7,7}))(?<CheckDigit>[0-9]\\s*)",
    "url": "https://wwwapps.ups.com/WebTracking/track?track=yes&trackNums=%s",
    "checksum": {
      "name": "mod10",
      "evens": 1,
      "odds": 2,
      "reverse": false,
      "weightings": null,
      "modulo1": null,
      "modulo2": null
    },
    "prependIf": null
  },
  {
    "id": "ups-UPS Waybill",
    "courier": "UPS",
    "courierCode": "ups",
    "name": "UPS Waybill",
    "source": "\\s*(?<ServiceType>([AHJKTV]\\s*){1})(?<SerialNumber>(?:[0-9]\\s*){9})(?<CheckDigit>[0-9]\\s*){1}",
    "url": "https://wwwapps.ups.com/WebTracking/track?track=yes&trackNums=%s",
    "checksum": {
      "name": "mod10",
      "evens": 1,
      "odds": 2,
      "reverse": false,
      "weightings": null,
      "modulo1": null,
      "modulo2": null
    },
    "prependIf": null
  },
  {
    "id": "usps_20",
    "courier": "United States Postal Service",
    "courierCode": "usps",
    "name": "USPS 20",
    "source": "\\s*(?<SerialNumber>(?<ServiceType>([0-9]\\s*){2})(?<ShipperId>([0-9]\\s*){9})(?<PackageId>([0-9]\\s*){8}))(?<CheckDigit>[0-9]\\s*)",
    "url": "https://tools.usps.com/go/TrackConfirmAction?tLabels=%s",
    "checksum": {
      "name": "mod10",
      "evens": 3,
      "odds": 1,
      "reverse": false,
      "weightings": null,
      "modulo1": null,
      "modulo2": null
    },
    "prependIf": null
  },
  {
    "id": "usps_22",
    "courier": "United States Postal Service",
    "courierCode": "usps",
    "name": "USPS 22",
    "source": "\\s*((?<RoutingApplicationId>4\\s*2\\s*0\\s*)(?<DestinationZip>([0-9]\\s*){5}))?(?<SerialNumber>(?<ServiceType>(9\\s*[4-8]\\s*))(?<ShipperId>([0-9]\\s*){9})(?<PackageId>([0-9]\\s*){10}))(?<CheckDigit>[0-9]\\s*)",
    "url": "https://tools.usps.com/go/TrackConfirmAction?tLabels=%s",
    "checksum": {
      "name": "mod10",
      "evens": 3,
      "odds": 1,
      "reverse": true,
      "weightings": null,
      "modulo1": null,
      "modulo2": null
    },
    "prependIf": null
  },
  {
    "id": "usps_32V2",
    "courier": "United States Postal Service",
    "courierCode": "usps",
    "name": "USPS 34v2",
    "source": "\\s*(?<RoutingApplicationId>4\\s*2\\s*0\\s*)(?<DestinationZip>([0-9]\\s*){5})(?<RoutingNumber>([0-9]\\s*){4})(?<SerialNumber>(?<ApplicationIdentifier>9\\s*[2345]\\s*)?(?<ShipperId>([0-9]\\s*){8})(?<PackageId>([0-9]\\s*){11}))(?<CheckDigit>[0-9]\\s*)",
    "url": "https://tools.usps.com/go/TrackConfirmAction?tLabels=%s",
    "checksum": {
      "name": "mod10",
      "evens": 3,
      "odds": 1,
      "reverse": false,
      "weightings": null,
      "modulo1": null,
      "modulo2": null
    },
    "prependIf": null
  },
  {
    "id": "usps_91",
    "courier": "United States Postal Service",
    "courierCode": "usps",
    "name": "USPS 91",
    "source": "\\s*(?:(?<RoutingApplicationId>4\\s*2\\s*0\\s*)(?<DestinationZip>([0-9]\\s*){5}))?(?<SerialNumber>(?<ApplicationIdentifier>9\\s*[12345]\\s*)?(?<SCNC>([0-9]\\s*){2})(?<ServiceType>([0-9]\\s*){2})(?<ShipperId>([0-9]\\s*){8})(?<PackageId>([0-9]\\s*){11}|([0-9]\\s*){7}))(?<CheckDigit>[0-9]\\s*)",
    "url": "https://tools.usps.com/go/TrackConfirmAction?tLabels=%s",
    "checksum": {
      "name": "mod10",
      "evens": 3,
      "odds": 1,
      "reverse": false,
      "weightings": null,
      "modulo1": null,
      "modulo2": null
    },
    "prependIf": {
      "unless": "^(?!9[1-5]).+",
      "content": "91"
    }
  }
];

/**
 * ISO 3166-1 alpha-2 to national postal operator, from the UPU S10 standard.
 * One entry per member country, which is why a single pattern resolves
 * "EE123456789IN" to India Post and "CP123456789FR" to La Poste.
 */
export const S10_COURIERS: Readonly<Record<string, string>> = {
  "AF": "Afghan Post",
  "AL": "Posta Shqiptare",
  "DZ": "Algérie Poste",
  "AO": "Correios de Angola",
  "AG": "Antigua Postal Services",
  "AR": "Correo Argentino",
  "AM": "Haypost - Armenian Postal Service",
  "AU": "Australia Post",
  "AT": "Österreichische Post AG",
  "AZ": "Azarpoçt",
  "BS": "Bahamas Postal Service",
  "BH": "Bahrain Post",
  "BD": "Bangladesh Post Office",
  "BB": "Barbados Postal Service",
  "BY": "Belpochta",
  "BE": "bpost",
  "BZ": "Belize Postal Service",
  "BJ": "La Poste du Bénin",
  "BT": "Bhutan Post",
  "BO": "ECOBOL – Empresa de Correos de Bolivia",
  "BA": "JP BH POŠTA d.o.o. Sarajevo",
  "BW": "BotswanaPost",
  "BR": "CORREIOS",
  "BN": "Brunei Postal Services",
  "BG": "Bulgarian Posts",
  "BF": "SONAPOST",
  "BI": "RNP – Régie nationale des postes",
  "KH": "Ministry of Posts and Telecommunications",
  "CM": "CAMPOST – Cameroon Postal Services",
  "CA": "Canada Post",
  "CV": "Correios de Cabo Verde",
  "CF": "Direction des services postaux de l'Office National des Postes et de l'Épargne",
  "TD": "Société tchadienne des postes et de l'épargne",
  "CL": "Correos de Chile",
  "CN": "China Post",
  "HK": "Hong Kong Post",
  "CO": "4-72 La Red Postal de Colombia",
  "KM": "Societé Nationale des Postes et des Services Financiers",
  "CG": "Congolese Posts and Savings Company",
  "CR": "Correos de Costa Rica",
  "HR": "Hrvatska Posta - Croatian Post",
  "CU": "Ministerio de la Informática y las comunicaciones de Cuba",
  "CY": "Cyprus Post",
  "CZ": "Česká Pošta",
  "CI": "La Poste de Côte d’Ivoire",
  "KP": "Korea Post and Telecommunications Corporation",
  "CD": "Congolese Posts and Telecommunications Corporation",
  "DK": "Post Danmark",
  "DJ": "La Poste de Djibouti",
  "DM": "General Post Office",
  "DO": "INPOSDOM – Instituto Postal Dominicano",
  "EC": "Correos del Ecuador",
  "EG": "Egypt Post",
  "SV": "Correos de El Salvador",
  "GQ": "Equatorial Guinea Post",
  "ER": "Eritrean Postal Service",
  "EE": "Eesti Post",
  "ET": "Ethiopian postal service",
  "FJ": "Post Fiji",
  "FI": "Posti Ltd",
  "FR": "La Poste",
  "GA": "La Poste SA",
  "GM": "Gambia Postal services Corporation",
  "GE": "Georgian Post",
  "DE": "Deutsche Post",
  "GH": "Ghana Post",
  "GB": "Royal Mail Group plc",
  "GR": "Hellenic Post ELTA",
  "GD": "Grenada Postal Corporation",
  "GT": "El Correo",
  "GN": "Office de la poste guinéenne",
  "GW": "Correios da Guiné-Bissau",
  "GY": "Guyana Post Office Corporation",
  "HT": "Office des Postes d’Haiti",
  "HN": "Honducor",
  "HU": "Magyar Posta",
  "IS": "Íslandspóstur hf",
  "IN": "India Post",
  "ID": "Pos Indonesia",
  "IR": "Islamic Republic of Iran Post Co.",
  "IQ": "Iraqi Post",
  "IE": "AN Post - regulatory and International affairs Unit",
  "IL": "Israel Post",
  "IT": "Poste Italiane",
  "JM": "Jamaica Post",
  "JP": "Japan Post",
  "JO": "Jordan Post",
  "KZ": "Kazpost",
  "KE": "Posta Kenya",
  "KI": "Kiribati Public Service Public",
  "KR": "Korea Post",
  "KW": "Kuwait Ministry of Communications",
  "KG": "Kyrgyz Post",
  "LA": "Entreprise des Postes Lao",
  "LV": "Latvia Post",
  "LB": "LibanPost",
  "LS": "Lesotho Post",
  "LR": "Ministry of Posts and Telecommunications",
  "LY": "Libya Post",
  "LI": "Liechtensteinische Post AG",
  "LT": "Lietuvos Pastas",
  "LU": "Post",
  "MG": "PAOSITRA MALAGASY",
  "MW": "Malawi Posts Corporation",
  "MY": "Pos Malaysia",
  "MV": "Maldives Post",
  "ML": "Office national des postes",
  "MT": "Malta Post",
  "MR": "MAURIPOST – Société Mauritanienne des Postes",
  "MU": "Mauritius Post",
  "MX": "Correos de México",
  "MD": "Posta Moldovei",
  "MC": "La Poste Monaco",
  "MN": "Mongol Post - Монгол шуудан компани",
  "ME": "Pošta Crne Gore",
  "MA": "Barid Al-Maghrib – Poste Maroc",
  "MZ": "Correios de Moçambique",
  "MM": "Myanmar Post and Telecommunications Department",
  "NA": "NAM Post",
  "NR": "Nauru General Post Office",
  "NP": "Nepal Postal Services",
  "NL": "PostNL",
  "NZ": "New Zealand Post",
  "NI": "Correos de Nicaragua",
  "NE": "Niger Poste",
  "NG": "Nigerian Postal Service",
  "NO": "Posten",
  "OM": "Oman Post",
  "PK": "Pakistan Post",
  "PA": "Correos de Panamá",
  "PG": "Post PNG",
  "PY": "Correo Paraguayo",
  "PE": "SERPOST – Servicios Postales del Perú",
  "PH": "PHLPOST – Philippine Postal Corporation",
  "PL": "Poczta Polska",
  "PT": "CTT - Correios",
  "QA": "Qatar Post",
  "RO": "Posta Romana",
  "RU": "Russian Post",
  "RW": "National Post Office (Iposita)",
  "KN": "St. Kitts & Nevis Postal Services",
  "LC": "Saint Lucia Postal Service",
  "VC": "SVG Postal Corporation",
  "WS": "Samoa Post",
  "SM": "Poste San Marino",
  "ST": "Correios de São Tomé e Príncipe",
  "SA": "Saudi Post",
  "SN": "La Poste Senegal",
  "RS": "PTT Communications \"Srbija\"",
  "SC": "Seychelles Postal Service",
  "SL": "Sierra Leone Postal Services",
  "SG": "SingPost",
  "SK": "Slovenská Posta",
  "SI": "Posta Slovenije d.o.o.",
  "SB": "Solomon Post",
  "SO": "Somali Post",
  "ZA": "South African Post Office",
  "SS": "Minister of Telecommunication and Postal Services",
  "ES": "Correos y Telégrafos",
  "LK": "Sri Lanka Post",
  "SD": "Sudapost",
  "SR": "SURPOST",
  "SZ": "Swaziland Posts & Telecommunications Corporation",
  "SE": "Posten Sweden Post",
  "CH": "La Poste Suisse",
  "SY": "Syrian Post",
  "TJ": "Tajikistan’s communications service agency",
  "TZ": "Tanzania Posts Corporation",
  "TH": "Thailand Post",
  "MK": "Macedonian Post & Telecommunications",
  "TL": "Correios de Timor Leste",
  "TG": "La Poste du Togo",
  "TO": "Tonga Post",
  "TT": "Trinidad and Tobago Postal Corporation",
  "TN": "La Poste Tunisienne",
  "TR": "Turkey Post",
  "TM": "Turkmenpost",
  "TV": "Tuvalu Philatelic Bureau",
  "UG": "Posta Uganda",
  "UA": "Ukrposhta",
  "AE": "Emirates Post",
  "US": "United States Postal Service",
  "UY": "Correo Uruguayo",
  "UZ": "Post of Uzbekistan",
  "VU": "Vanuatu Post",
  "VA": "Vatican post",
  "VE": "IPOSTEL – Instituto Postal Telegráfico de Venezuela",
  "VN": "VNPT – Vietnam Posts and Telecommunications Group",
  "YE": "Yemen Post",
  "ZM": "Zambia Postal Services Corporation (ZAMPOST)",
  "ZW": "Zimpost – Zimbabwe Posts"
};
